import { t } from '../../i18n';

export interface ModelManagerStrings {
	title: string;
	viewModels: string;
	viewConnections: string;
	viewVision: string;
	scope: string;
	refresh: string;
	loading: string;
	modelsHeading: string;
	modelsDescription: string;
	model: string;
	apiModelId: string;
	connection: string;
	imageMode: string;
	status: string;
	addModel: string;
	noModels: string;
	inspectorTitle: string;
	modelName: string;
	modelId: string;
	endpointRoute: string;
	visionMode: string;
	visionProxy: string;
	visionProxyHint: string;
	nativeImages: string;
	nativeBudgetHint: string;
	mcpImages: string; // [FORK] mcp mode label
	mcpBudgetHint: string; // [FORK] mcp mode hint
	contextWindow: string;
	maxOutput: string;
	toolCalling: string;
	thinking: string;
	valueSource: string;
	saveChanges: string;
	resetOverride: string;
	deleteModel: string;
	close: string;
	customModelTitle: string;
	customModelIdHint: string;
	connectionsHeading: string;
	connectionsDescription: string;
	defaultEndpoint: string;
	customBaseUrl: string;
	customBaseUrlHint: string;
	resolvedUrl: string;
	protocol: string;
	credentialChannel: string;
	keyConfigured: string;
	keyMissing: string;
	saveConnection: string;
	credentialsHeading: string;
	credentialsDescription: string;
	modelsUsing: string;
	setKey: string;
	replaceKey: string;
	clearKey: string;
	getKey: string;
	visionHeading: string;
	visionDescription: string;
	visionSource: string;
	visionAuto: string;
	visionVscodeLm: string;
	visionApiEndpoint: string;
	visionModel: string;
	endpointUrl: string;
	endpointType: string;
	selectEndpointType: string;
	endpointOpenAIChat: string;
	endpointOpenAIResponses: string;
	endpointAnthropic: string;
	apiKey: string;
	apiKeyConfiguredHint: string;
	apiKeyMissingHint: string;
	customHeaders: string;
	customHeadersConfiguredHint: string;
	customHeadersEmptyHint: string;
	extraBody: string;
	testConnection: string;
	saveVision: string;
	clearVisionKey: string;
	testImage: string;
	testResponse: string;
	noSelection: string;
	invalidNumber: string;
	invalidJson: string;
	fieldRequired: string;
	nonCanonicalModelId: string;
	working: string;
}

export function getModelManagerStrings(): ModelManagerStrings {
	return {
		title: t('manager.title'),
		viewModels: t('manager.view.models'),
		viewConnections: t('manager.view.connections'),
		viewVision: t('manager.view.vision'),
		scope: t('manager.scope'),
		refresh: t('manager.action.refresh'),
		loading: t('manager.loading'),
		modelsHeading: t('manager.models.heading'),
		modelsDescription: t('manager.models.description'),
		model: t('manager.column.model'),
		apiModelId: t('manager.column.apiModelId'),
		connection: t('manager.column.connection'),
		imageMode: t('manager.column.imageMode'),
		status: t('manager.column.status'),
		addModel: t('manager.action.addModel'),
		noModels: t('manager.models.empty'),
		inspectorTitle: t('manager.inspector.title'),
		modelName: t('manager.field.modelName'),
		modelId: t('manager.field.modelId'),
		endpointRoute: t('manager.field.endpointRoute'),
		visionMode: t('manager.field.visionMode'),
		visionProxy: t('manager.visionMode.proxy'),
		visionProxyHint: t('manager.visionMode.proxyHint'),
		nativeImages: t('manager.visionMode.native'),
		nativeBudgetHint: t('manager.visionMode.nativeHint'),
		mcpImages: t('manager.visionMode.mcp'), // [FORK]
		mcpBudgetHint: t('manager.visionMode.mcpHint'), // [FORK]
		contextWindow: t('manager.field.contextWindow'),
		maxOutput: t('manager.field.maxOutput'),
		toolCalling: t('manager.field.toolCalling'),
		thinking: t('manager.field.thinking'),
		valueSource: t('manager.field.valueSource'),
		saveChanges: t('manager.action.saveChanges'),
		resetOverride: t('manager.action.resetOverride'),
		deleteModel: t('manager.action.deleteModel'),
		close: t('manager.action.close'),
		customModelTitle: t('manager.customModel.title'),
		customModelIdHint: t('manager.customModel.idHint'),
		connectionsHeading: t('manager.connections.heading'),
		connectionsDescription: t('manager.connections.description'),
		defaultEndpoint: t('manager.field.defaultEndpoint'),
		customBaseUrl: t('manager.field.customBaseUrl'),
		customBaseUrlHint: t('manager.field.customBaseUrlHint'),
		resolvedUrl: t('manager.field.resolvedUrl'),
		protocol: t('manager.field.protocol'),
		credentialChannel: t('manager.field.credentialChannel'),
		keyConfigured: t('manager.key.configured'),
		keyMissing: t('manager.key.missing'),
		saveConnection: t('manager.action.saveConnection'),
		credentialsHeading: t('manager.credentials.heading'),
		credentialsDescription: t('manager.credentials.description'),
		modelsUsing: t('manager.credentials.modelsUsing'),
		setKey: t('manager.action.setKey'),
		replaceKey: t('manager.action.replaceKey'),
		clearKey: t('manager.action.clearKey'),
		getKey: t('manager.action.getKey'),
		visionHeading: t('manager.vision.heading'),
		visionDescription: t('manager.vision.description'),
		visionSource: t('vision.panel.field.source'),
		visionAuto: t('vision.panel.source.auto'),
		visionVscodeLm: t('vision.panel.source.vscodeLm'),
		visionApiEndpoint: t('vision.panel.source.apiEndpoint'),
		visionModel: t('vision.panel.field.visionModel'),
		endpointUrl: t('vision.panel.field.endpointUrl'),
		endpointType: t('vision.panel.field.endpointType'),
		selectEndpointType: t('vision.panel.placeholder.endpointType'),
		endpointOpenAIChat: t('vision.panel.endpointType.openaiChatCompletions'),
		endpointOpenAIResponses: t('vision.panel.endpointType.openaiResponses'),
		endpointAnthropic: t('vision.panel.endpointType.anthropicMessages'),
		apiKey: t('vision.panel.field.apiKey'),
		apiKeyConfiguredHint: t('vision.panel.hint.apiKeySet'),
		apiKeyMissingHint: t('vision.panel.hint.apiKeyUnset'),
		customHeaders: t('vision.panel.field.customHeaders'),
		customHeadersConfiguredHint: t('manager.vision.headersConfigured'),
		customHeadersEmptyHint: t('vision.panel.hint.customHeaders'),
		extraBody: t('vision.panel.field.extraBody'),
		testConnection: t('vision.panel.action.test'),
		saveVision: t('vision.panel.action.save'),
		clearVisionKey: t('vision.panel.action.clearApiKey'),
		testImage: t('vision.panel.test.image'),
		testResponse: t('vision.panel.test.response'),
		noSelection: t('manager.noSelection'),
		invalidNumber: t('manager.error.invalidNumber'),
		invalidJson: t('manager.error.invalidJson'),
		fieldRequired: t('manager.error.required'),
		nonCanonicalModelId: t('manager.error.nonCanonicalModelId'),
		working: t('manager.working'),
	};
}
